sudo: false
language: node_js
node_js:
  - 0.12
  - 0.10
  - 4.0
  - 4.1
matrix:
    allow_failures:
        - node_js: 4.0
        - node_js: 4.1
env:
    - TEST_SUITE=units
    - TEST_SUITE=functional
script: "npm run $TEST_SUITE"
